name: Build and Push Multi-Platform Docker Image

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch
  pull_request:
    branches:
      - main  # Optional: Trigger the action on pull requests to main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Step 2: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      # Step 3: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 4: Log in to GitHub Docker registry
      - name: Log in to GitHub Docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 5: Create and use a new Buildx builder
      - name: Create Buildx builder
        run: docker buildx create --use --name multi-builder

      # Step 6: Inspect the builder to verify platforms support
      - name: Inspect Buildx builder
        run: docker buildx inspect --bootstrap

      # Step 7: Build and push Docker image for multiple platforms
      - name: Build and Push Multi-Platform Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --tag ghcr.io/${{ github.repository }}:${{ github.sha }} \
            --tag ghcr.io/${{ github.repository }}:latest .

      # Optional Step 8: Clean up Buildx builder after build
      - name: Remove Buildx builder
        run: docker buildx rm multi-builder
