name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch
  pull_request:
    branches:
      - main  # Optional: Trigger the action on pull requests to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to GitHub Docker registry
      - name: Log in to GitHub Docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build . -t ghcr.io/${{ github.repository }}:${{ github.sha }}

      # Step 4: Push the Docker image to GitHub Packages
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

      # Step 5: Optionally, tag and push a 'latest' tag
      - name: Tag and push 'latest'
        if: github.ref == 'refs/heads/main'  # Only tag 'latest' for main branch
        run: |
          docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
